name: CI/CD deploy release
on: 
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]
jobs:
 ci_cd_deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'hello world'
